behaviors:
  AIRobotGeneric:
    trainer_type: ppo

    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0002
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear

    network_settings: 
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
     
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 20000
    threaded: true

    self_play:
      window: 20
      play_against_latest_model_ratio: 0.5
      save_steps: 25000
      team_change: 250000
      swap_steps: 50000


environment_parameters:
  team_dist_penalty_threshold: 0.3f
  team_dist_penalty: 0.02f
  max_steps: 2000
  max_arenas: 16
  ball_shape: 1 
  level: 1
  spawn_area_margin: 0.99
  random_obs_dist: 0.04
  random_obs_angle: 3
  number_of_blue_agents: 2
  number_of_red_agents: 2
  number_of_positive_energy_cores: 3
  number_of_negative_energy_cores: 3