behaviors:
  AIRobotGeneric:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 7
      learning_rate_schedule: linear

    network_settings: 
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: nature_cnn
      memory:
        memory_size: 128
        sequence_length: 64
        
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.99
        encoding_size: 128
        learning_rate: 0.0003

    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 20000
    threaded: true

    self_play:
      window: 20
      play_against_latest_model_ratio: 0.3
      save_steps: 50000
      team_change: 250000
      swap_steps: 25000


environment_parameters:
  max_steps:
    curriculum:
    - name: first_purple
      completion_criteria: &first_purple_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 3.5
        require_reset: true
      value: 3000
    - name: first_yellow
      completion_criteria: &first_yellow_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 3.5
        require_reset: true
      value: 3000

    - name: second_purple
      completion_criteria: &second_purple_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 5
        require_reset: true
      value: 2000
    - name: second_yellow
      completion_criteria: &second_yellow_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 5
        require_reset: true
      value: 2000

    - name: two_balls
      completion_criteria: &two_balls_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8
        require_reset: true
      value: 2000
    - name: 2b2b
      completion_criteria: &2b2b_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8
        require_reset: true
      value: 2000

    - name: first_fight
      completion_criteria: &first_fight_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8
        require_reset: true
      value: 2000
    - name: two_on_two
      completion_criteria: &two_on_two_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8
        require_reset: true
      value: 2000

    - name: big_fight
      completion_criteria: &big_fight_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 10
        require_reset: true
      value: 3000
    - name: mega_fight
      completion_criteria: &mega_fight_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 10
        require_reset: true
      value: 3000

    - name: freeplay
      value: 2000
  

  max_arenas:
    curriculum:
      - name: first_purple
        completion_criteria: *first_purple_defaults
        value: 128
      - name: first_yellow
        completion_criteria: *first_yellow_defaults
        value: 128

      - name: second_purple
        completion_criteria: *second_purple_defaults
        value: 64
      - name: second_yellow
        completion_criteria: *second_yellow_defaults
        value: 64

      - name: two_balls
        completion_criteria: *two_balls_defaults
        value: 32
      - name: 2b2b
        completion_criteria: *2b2b_defaults
        value: 32

      - name: first_fight
        completion_criteria: *first_fight_defaults
        value: 32
      - name: two_on_two
        completion_criteria: *two_on_two_defaults
        value: 32

      - name: big_fight
        completion_criteria: *big_fight_defaults
        value: 16
      - name: mega_fight
        completion_criteria: *mega_fight_defaults
        value: 16

      - name: freeplay
        value: 16


  ball_shape:
    curriculum:
      - name: first_purple
        value: 0
        completion_criteria: *first_purple_defaults
      - name: first_yellow
        value: 0
        completion_criteria: *first_yellow_defaults

      - name: second_purple
        completion_criteria: *second_purple_defaults
        value: 1
      - name: second_yellow
        completion_criteria: *second_yellow_defaults
        value: 1

      - name: two_balls
        completion_criteria: *two_balls_defaults
        value: 1
      - name: 2b2b
        completion_criteria: *2b2b_defaults
        value: 1

      - name: first_fight
        completion_criteria: *first_fight_defaults
        value: 1
      - name: two_on_two
        completion_criteria: *two_on_two_defaults
        value: 1

      - name: big_fight
        completion_criteria: *big_fight_defaults
        value: 1
      - name: mega_fight
        completion_criteria: *mega_fight_defaults
        value: 1

      - name: freeplay
        value: 1


  level:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 3
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 3

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 2
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 2

    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 2
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 2

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 1
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 1

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 1
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 1

    - name: freeplay
      value: 1


  spawn_area_margin:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0.5
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0.5

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0.7
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0.7

    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 0.8
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 0.88

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 0.9
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 0.9

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 0.95
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 0.95

    - name: freeplay
      value: 0.99


  random_obs_dist:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0.0
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0.0

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0.01
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0.01

    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 0.01
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 0.01

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 0.02
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 0.02

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 0.03
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 0.03

    - name: freeplay
      value: 0.04


  random_obs_angle:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0

    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0
    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0

    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 1
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 1

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 2
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 2

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 3
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 3

    - name: freeplay
      value: 4


  number_of_blue_agents:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 1
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 1

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 1  
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 1
 
    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 1
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 2

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 1
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 2

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 2
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 3

    - name: freeplay
      value: 2


  number_of_red_agents:
    curriculum:
    - name: first_purple
      value: 0
      completion_criteria: *first_purple_defaults
    - name: first_yellow
      value: 0
      completion_criteria: *first_yellow_defaults

    - name: first_yellow
      value: 0
      completion_criteria: *first_yellow_defaults
    - name: second_yellow
      value: 0
      completion_criteria: *second_purple_defaults

    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 0
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 0

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 1
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 2

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 2
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 3

    - name: freeplay
      value: 2


  number_of_positive_energy_cores:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 1

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 1

    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 1
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 1

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 1
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 2

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 3
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 5

    - name: freeplay
      value: 5

  number_of_negative_energy_cores:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 1
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 1
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0

    - name: two_balls
      completion_criteria: *two_balls_defaults
      value: 1
    - name: 2b2b
      completion_criteria: *2b2b_defaults
      value: 1

    - name: first_fight
      completion_criteria: *first_fight_defaults
      value: 1
    - name: two_on_two
      completion_criteria: *two_on_two_defaults
      value: 2

    - name: big_fight
      completion_criteria: *big_fight_defaults
      value: 3
    - name: mega_fight
      completion_criteria: *mega_fight_defaults
      value: 5

    - name: freeplay
      value: 5