behaviors:
  AIRobotGeneric:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 60000
    threaded: true
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000

environment_parameters:

  max_steps:
    curriculum:
    - name: first_purple
      completion_criteria: &first_purple_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 3.5
      value: 3500
    - name: first_yellow
      completion_criteria: &first_yellow_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 3.5
      value: 3500

    - name: second_purple
      completion_criteria: &second_purple_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 7
      value: 2000
    - name: second_yellow
      completion_criteria: &second_yellow_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 7
      value: 2000

    - name: Lesson5
      completion_criteria: &lesson5_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 6
      value: 2000
    - name: Lesson6
      completion_criteria: &lesson6_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 7
      value: 2000
    - name: Lesson7
      completion_criteria: &lesson7_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8
      value: 2000
    - name: Lesson8
      completion_criteria: &lesson8_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 8.5
      value: 2000
    - name: Lesson9
      completion_criteria: &lesson9_defaults
        measure: reward
        behavior: AIRobotGeneric
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 9
      value: 2000
    - name: Lesson10
      value: 2000
  
  max_arenas:
    curriculum:
      - name: first_purple
        completion_criteria: *first_purple_defaults
        value: 128
      - name: first_yellow
        completion_criteria: *first_yellow_defaults
        value: 128

      - name: Second_Purple
        value: 64
        completion_criteria: *second_purple_defaults
      - name: Second_Yellow
        value: 64
        completion_criteria: *second_yellow_defaults

      - name: Lesson5
        value: 16
        completion_criteria: *lesson5_defaults
      - name: Lesson6
        value: 16
        completion_criteria: *lesson6_defaults
      - name: Lesson7
        value: 16
        completion_criteria: *lesson7_defaults
      - name: Lesson8
        value: 16
        completion_criteria: *lesson8_defaults
      - name: Lesson9
        value: 16
        completion_criteria: *lesson9_defaults
      - name: Lesson10
        value: 16

  ball_shape:
    curriculum:
      - name: first_purple
        value: 0
        completion_criteria: *first_purple_defaults
      - name: first_yellow
        value: 0
        completion_criteria: *first_yellow_defaults

      - name: second_purple
        value: 1
        completion_criteria: *second_purple_defaults
      - name: second_yellow
        value: 1
        completion_criteria: *second_yellow_defaults

      - name: Lesson5
        completion_criteria: *lesson5_defaults
        value: 1
      - name: Lesson6
        completion_criteria: *lesson6_defaults
        value: 1
      - name: Lesson7
        completion_criteria: *lesson7_defaults
        value: 1
      - name: Lesson8
        completion_criteria: *lesson8_defaults
        value: 1
      - name: Lesson9
        completion_criteria: *lesson9_defaults
        value: 1
      - name: Lesson10
        value: 1

  level:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 3
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 3

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 2
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 2

    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 2
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 1
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 1
    - name: Lesson10
      value: 1

  spawn_area_margin:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0.5
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0.5

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0.7
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0.7

    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 0.8
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 0.85
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 0.9
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 0.99
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 0.99
    - name: Lesson10
      value: 0.99

  random_obs_dist:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0.0
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0.0

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0.01
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0.01


    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 0.01
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 0.01
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 0.02
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 0.02
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 0.02
    - name: Lesson10
      value: 0.02

  random_obs_angle:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0

    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0
    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0

    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 2
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 2
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 2
    - name: Lesson10
      value: 2

  number_of_blue_agents:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 1
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 1

    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 1  
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 1
 
    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 2
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 2
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 2
    - name: Lesson10
      value: 2

  number_of_red_agents:
    curriculum:
    - name: first_purple
      value: 0
      completion_criteria: *first_purple_defaults
    - name: first_yellow
      value: 0
      completion_criteria: *first_yellow_defaults

    - name: first_yellow
      value: 0
      completion_criteria: *first_yellow_defaults
    - name: second_yellow
      value: 0
      completion_criteria: *second_purple_defaults

    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 2
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 2
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 2
    - name: Lesson10
      value: 2

  number_of_positive_energy_cores:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 0
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 1
    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 0
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 1

    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 3
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 3
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 4
    - name: Lesson10
      value: 5

  number_of_negative_energy_cores:
    curriculum:
    - name: first_purple
      completion_criteria: *first_purple_defaults
      value: 1
    - name: first_yellow
      completion_criteria: *first_yellow_defaults
      value: 0
    - name: second_purple
      completion_criteria: *second_purple_defaults
      value: 1
    - name: second_yellow
      completion_criteria: *second_yellow_defaults
      value: 0

    - name: Lesson5
      completion_criteria: *lesson5_defaults
      value: 2
    - name: Lesson6
      completion_criteria: *lesson6_defaults
      value: 2
    - name: Lesson7
      completion_criteria: *lesson7_defaults
      value: 3
    - name: Lesson8
      completion_criteria: *lesson8_defaults
      value: 3
    - name: Lesson9
      completion_criteria: *lesson9_defaults
      value: 4
    - name: Lesson10
      value: 5